-- Performance — switch bundled catalog art to the optimized WebP files
-- (generated by `npm run images`; ~96% smaller than the PNGs).
-- Run after 0005_hero.sql. Safe to re-run (idempotent replaces).
--
-- Only /models/*.png paths are rewritten: admin-uploaded Storage URLs are
-- untouched, and order_items.image snapshots keep their original .png paths
-- (those files remain in the repo).

update public.product_images
  set url = replace(url, '.png', '.webp')
  where url like '/models/%.png';

-- Hero image: rewrite only if it still points at a bundled /models/ png.
update public.settings
  set hero = jsonb_set(hero, '{image}',
    to_jsonb(replace(hero->>'image', '.png', '.webp')))
  where id = 1
    and hero ? 'image'
    and hero->>'image' like '/models/%.png';
